# Generated by Django 5.2 on 2025-05-07 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_produit_image_panieritem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='panieritem',
            unique_together={('user', 'produit')},
        ),
        migrations.AddField(
            model_name='panieritem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='panieritem',
            name='quantite',
        ),
    ]
