# Generated by Django 5.2 on 2025-05-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_equipement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='poids_max',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='prix_original',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='produit',
        ),
        migrations.AddField(
            model_name='equipement',
            name='description',
            field=models.TextField(default='Aucune description'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='image',
            field=models.ImageField(default='equipement/default.jpg', upload_to='equipement/'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='nom',
            field=models.CharField(default='Nom inconnu', max_length=255),
        ),
    ]
