# Generated by Django 5.2 on 2025-05-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_equipement_dimensions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipement',
        ),
    ]
