# Generated by Django 5.2.1 on 2025-05-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_panierutilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipementFitness',
        ),
        migrations.RemoveField(
            model_name='panierutilisateur',
            name='user',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='stock',
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('chaussures', 'Chaussures'), ('fitness', 'Fitness & Musculation'), ('autres', 'Autres')], default='autres', max_length=50),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(upload_to='produits/'),
        ),
        migrations.DeleteModel(
            name='PanierItem',
        ),
        migrations.DeleteModel(
            name='PanierUtilisateur',
        ),
    ]
