# Generated by Django 5.2.1 on 2025-05-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('chaussures', 'Chaussures'), ('vetements', 'Vêtements Sportif'), ('fitness', 'Fitness & Musculation'), ('autres', 'Autres')], default='autres', max_length=50),
        ),
    ]
