# Generated by Django 5.2.1 on 2025-05-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='genre',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('enfant', 'Enfant')], default='homme', max_length=10),
        ),
    ]
