# Generated by Django 5.2.1 on 2025-05-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_produit_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('chaussures', 'Chaussures'), ('vetements', 'Vêtements Sportif'), ('fitness', 'Fitness & Musculation'), ('velo', 'Vélo')], default='autres', max_length=50),
        ),
    ]
