# Generated by Django 5.2.1 on 2025-05-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='panieritem',
            name='taille',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='tailles_disponibles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
